export enum EstadoMexicoCodigo {
  Aguascalientes = 'AGU',
  BajaCalifornia = 'BCN',
  BajaCaliforniaSur = 'BCS',
  Campeche = 'CAM',
  Chiapas = 'CHP',
  Chihuahua = 'CHH',
  CiudadDeMexico = 'CMX',
  Coahuila = 'COA',
  Colima = 'COL',
  Durango = 'DUR',
  Guanajuato = 'GUA',
  Guerrero = 'GRO',
  Hidalgo = 'HID',
  Jalisco = 'JAL',
  Michoacan = 'MIC',
  Morelos = 'MOR',
  Mexico = 'MEX',
  Nayarit = 'NAY',
  NuevoLeon = 'NLE',
  Oaxaca = 'OAX',
  Puebla = 'PUE',
  Queretaro = 'QUE',
  QuintanaRoo = 'ROO',
  SanLuisPotosi = 'SLP',
  Sinaloa = 'SIN',
  Sonora = 'SON',
  Tabasco = 'TAB',
  Tamaulipas = 'TAM',
  Tlaxcala = 'TLA',
  Veracruz = 'VER',
  Yucatan = 'YUC',
  Zacatecas = 'ZAC'
}

export const ESTADOS_MX_OPTIONS = [
  { value: EstadoMexicoCodigo.Aguascalientes, label: 'Aguascalientes' },
  { value: EstadoMexicoCodigo.BajaCalifornia, label: 'Baja California' },
  { value: EstadoMexicoCodigo.BajaCaliforniaSur, label: 'Baja California Sur' },
  { value: EstadoMexicoCodigo.Campeche, label: 'Campeche' },
  { value: EstadoMexicoCodigo.Chiapas, label: 'Chiapas' },
  { value: EstadoMexicoCodigo.Chihuahua, label: 'Chihuahua' },
  { value: EstadoMexicoCodigo.CiudadDeMexico, label: 'Ciudad de Mexico' },
  { value: EstadoMexicoCodigo.Coahuila, label: 'Coahuila' },
  { value: EstadoMexicoCodigo.Colima, label: 'Colima' },
  { value: EstadoMexicoCodigo.Durango, label: 'Durango' },
  { value: EstadoMexicoCodigo.Guanajuato, label: 'Guanajuato' },
  { value: EstadoMexicoCodigo.Guerrero, label: 'Guerrero' },
  { value: EstadoMexicoCodigo.Hidalgo, label: 'Hidalgo' },
  { value: EstadoMexicoCodigo.Jalisco, label: 'Jalisco' },
  { value: EstadoMexicoCodigo.Michoacan, label: 'Michoacan' },
  { value: EstadoMexicoCodigo.Morelos, label: 'Morelos' },
  { value: EstadoMexicoCodigo.Mexico, label: 'Estado de Mexico' },
  { value: EstadoMexicoCodigo.Nayarit, label: 'Nayarit' },
  { value: EstadoMexicoCodigo.NuevoLeon, label: 'Nuevo Leon' },
  { value: EstadoMexicoCodigo.Oaxaca, label: 'Oaxaca' },
  { value: EstadoMexicoCodigo.Puebla, label: 'Puebla' },
  { value: EstadoMexicoCodigo.Queretaro, label: 'Queretaro' },
  { value: EstadoMexicoCodigo.QuintanaRoo, label: 'Quintana Roo' },
  { value: EstadoMexicoCodigo.SanLuisPotosi, label: 'San Luis Potosi' },
  { value: EstadoMexicoCodigo.Sinaloa, label: 'Sinaloa' },
  { value: EstadoMexicoCodigo.Sonora, label: 'Sonora' },
  { value: EstadoMexicoCodigo.Tabasco, label: 'Tabasco' },
  { value: EstadoMexicoCodigo.Tamaulipas, label: 'Tamaulipas' },
  { value: EstadoMexicoCodigo.Tlaxcala, label: 'Tlaxcala' },
  { value: EstadoMexicoCodigo.Veracruz, label: 'Veracruz' },
  { value: EstadoMexicoCodigo.Yucatan, label: 'Yucatan' },
  { value: EstadoMexicoCodigo.Zacatecas, label: 'Zacatecas' }
] as const;

export const ESTADOS_MX_CODES = new Set<string>(ESTADOS_MX_OPTIONS.map((option) => option.value));
