"""Fachada de compatibilidad del paquete `core`.

El código de esta capa vivía en un único archivo de 2,000 líneas que mezclaba
acceso a datos, red, configuración, seguridad, correo y logging: todo lo que
tocaba algo importaba todo, y el prefijo `_` había dejado de significar
"privado" porque los lambdas usaban ~76 de esos símbolos.

Ahora vive en `core/`, un módulo por responsabilidad y con las dependencias
en una sola dirección (ver `core/__init__.py`). Este archivo se conserva para
que los ~280 puntos de llamada existentes (`import core_utils as utils`) sigan
funcionando sin tocarlos; el código nuevo debería importar del módulo concreto:

    from core.db import _query_bucket        # en vez de utils._query_bucket
"""
# ruff: noqa: F401  (fachada: todo lo importado aquí es reexportación)

from core.settings import (
    APP_CONFIG_TTL_SECONDS,
    AWS_REGION,
    BUCKET_NAME,
    COMMISSION_MONTH_PK,
    D_CENT,
    D_ONE,
    D_ZERO,
    LEDGER_MAX_ATTEMPTS,
    MAX_BATCH_GET_RETRIES,
    MAX_NETWORK_DEPTH,
    NETWORK_TREE_ID,
    NETWORK_TREE_ROOT_KEY,
    NETWORK_TREE_SK,
    PASSWORD_HASH_ITERATIONS,
    PASSWORD_HASH_SCHEME,
    SESSION_TTL_SECONDS,
    SES_FROM_EMAIL,
    TABLE_NAME,
    _ALL_PRIVILEGES,
    _SUPERADMIN_TOKEN,
)
from core.domain import (
    CommissionMonthStatus,
    CommissionStatus,
    OrderStatus,
)
from core.values import (
    _associate_month_entity_id,
    _customer_entity_id,
    _customer_id_list,
    _customer_id_str,
    _dedupe_ddb_keys,
    _json_default,
    _merge_dict,
    _month_key,
    _normalize_ddb_key,
    _normalize_email,
    _now_iso,
    _to_decimal,
    _ttl_epoch,
)
from core.logs import (
    _log,
    _log_default,
    _log_error,
    _log_get_item_failure,
)
from core.http import (
    HttpRequest,
    _cors_headers,
    _cors_preflight_response,
    _handle_unexpected,
    _http_request,
    _json_response,
    _parse_body,
)
from core.db import (
    _ENTITY_ID_NORMALIZERS,
    register_entity_id_normalizer,
    _ENTITY_BATCH_LOADERS,
    _ENTITY_READERS,
    _batch_get_entities,
    _batch_get_items,
    _bucket_pk,
    _ddb_client,
    _ddb_deserialize_item,
    _ddb_deserializer,
    _ddb_key_request_shape,
    _ddb_serialize_item,
    _ddb_serialize_key,
    _ddb_serializer,
    _dynamodb,
    _get_by_id,
    _get_item_by_key,
    _iter_bucket,
    _make_bucket_sk,
    _normalize_batch_entity_id,
    _put_entity,
    _put_entity_atomic,
    _query_all_pages,
    _query_bucket,
    _ref_pk,
    _safe_get_item,
    _table,
    _update_by_id,
    register_entity_batch_loader,
    register_entity_reader,
)
from core.config import (
    _activation_mxn,
    _activation_vp,
    _app_config_cache,
    _default_app_config,
    _invalidate_app_config_cache,
    _load_app_config,
    _max_network_levels,
    _mxn_per_vp,
    _normalize_app_config,
)
from core.network import (
    _associate_month_key,
    _batch_get_associate_months,
    _build_network_tree_payload,
    _build_order_customer_history_item,
    _ensure_network_tree,
    _get_associate_month_by_id,
    _get_customer_upline_ids,
    _get_network_tree,
    _get_network_tree_legacy,
    _increment_associate_month_net_volume,
    _increment_associate_month_net_vp,
    _load_month_states,
    _load_network_scope,
    _migrate_associate_month_item,
    _network_tree_descendant_ids,
    _network_tree_key,
    _normalize_network_tree_item,
    _order_customer_history_pk,
    _order_customer_history_sk,
    _put_associate_month_ref,
    _put_network_tree,
    _sync_customer_network_metadata,
    _upsert_order_customer_history,
)
from core.entities import (
    _normalize_associate_month_id,
)
from core.indexes import (
    _customer_email_index_key,
    _customer_name_index_pk,
    _find_customer_id_by_email,
    _query_customer_name_index,
    _referral_code_pk,
    _upsert_customer_email_index,
    _upsert_customer_name_index,
)
from core.ledger import (
    _LedgerConflict,
    _get_ledger_month,
    _ledger_sk,
    _mutate_ledger_month,
    _recalc_ledger_totals,
    _save_ledger_month,
    _void_ledger_rows_for_order,
)
from core.security import (
    _extract_actor,
    _extract_actor_from_bearer,
    _extract_admin_actor,
    _extract_bearer_token,
    _hash_password,
    _hash_token,
    _is_legacy_password_hash,
    _normalize_privileges,
    _require_admin,
    _require_self_or_admin,
    _require_self_or_admin_from_bearer,
    _superadmin_actor,
    _verify_password,
)
from core.email import (
    _get_ses,
    _send_ses_email,
    _ses_client,
)
from core.audit import (
    _audit_event,
)

# Los lambdas alcanzan estos a través de `utils.*`; se reexportan a propósito.
import base64
import hashlib
import hmac
import json
import os
import time
import uuid
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple
import boto3
from boto3.dynamodb.types import TypeDeserializer, TypeSerializer
from boto3.dynamodb.conditions import Attr, Key
from botocore.exceptions import ClientError


# `__all__` documenta la superficie de la fachada y evita que el analizador
# estático marque cada reexportación como import sin usar.
__all__ = [
    "_ENTITY_ID_NORMALIZERS",
    "_normalize_associate_month_id",
    "register_entity_id_normalizer",
    "APP_CONFIG_TTL_SECONDS",
    "AWS_REGION",
    "Any",
    "Attr",
    "BUCKET_NAME",
    "COMMISSION_MONTH_PK",
    "ClientError",
    "CommissionMonthStatus",
    "CommissionStatus",
    "D_CENT",
    "D_ONE",
    "D_ZERO",
    "Decimal",
    "Dict",
    "HttpRequest",
    "Key",
    "LEDGER_MAX_ATTEMPTS",
    "List",
    "MAX_BATCH_GET_RETRIES",
    "MAX_NETWORK_DEPTH",
    "NETWORK_TREE_ID",
    "NETWORK_TREE_ROOT_KEY",
    "NETWORK_TREE_SK",
    "Optional",
    "OrderStatus",
    "PASSWORD_HASH_ITERATIONS",
    "PASSWORD_HASH_SCHEME",
    "SESSION_TTL_SECONDS",
    "SES_FROM_EMAIL",
    "TABLE_NAME",
    "Tuple",
    "TypeDeserializer",
    "TypeSerializer",
    "_ALL_PRIVILEGES",
    "_ENTITY_BATCH_LOADERS",
    "_ENTITY_READERS",
    "_LedgerConflict",
    "_SUPERADMIN_TOKEN",
    "_activation_mxn",
    "_activation_vp",
    "_app_config_cache",
    "_associate_month_entity_id",
    "_associate_month_key",
    "_audit_event",
    "_batch_get_associate_months",
    "_batch_get_entities",
    "_batch_get_items",
    "_bucket_pk",
    "_build_network_tree_payload",
    "_build_order_customer_history_item",
    "_cors_headers",
    "_cors_preflight_response",
    "_customer_email_index_key",
    "_customer_entity_id",
    "_customer_id_list",
    "_customer_id_str",
    "_customer_name_index_pk",
    "_ddb_client",
    "_ddb_deserialize_item",
    "_ddb_deserializer",
    "_ddb_key_request_shape",
    "_ddb_serialize_item",
    "_ddb_serialize_key",
    "_ddb_serializer",
    "_dedupe_ddb_keys",
    "_default_app_config",
    "_dynamodb",
    "_ensure_network_tree",
    "_extract_actor",
    "_extract_actor_from_bearer",
    "_extract_admin_actor",
    "_extract_bearer_token",
    "_find_customer_id_by_email",
    "_get_associate_month_by_id",
    "_get_by_id",
    "_get_customer_upline_ids",
    "_get_item_by_key",
    "_get_ledger_month",
    "_get_network_tree",
    "_get_network_tree_legacy",
    "_get_ses",
    "_handle_unexpected",
    "_hash_password",
    "_hash_token",
    "_http_request",
    "_increment_associate_month_net_volume",
    "_increment_associate_month_net_vp",
    "_invalidate_app_config_cache",
    "_is_legacy_password_hash",
    "_iter_bucket",
    "_json_default",
    "_json_response",
    "_ledger_sk",
    "_load_app_config",
    "_load_month_states",
    "_load_network_scope",
    "_log",
    "_log_default",
    "_log_error",
    "_log_get_item_failure",
    "_make_bucket_sk",
    "_max_network_levels",
    "_merge_dict",
    "_migrate_associate_month_item",
    "_month_key",
    "_mutate_ledger_month",
    "_mxn_per_vp",
    "_network_tree_descendant_ids",
    "_network_tree_key",
    "_normalize_app_config",
    "_normalize_batch_entity_id",
    "_normalize_ddb_key",
    "_normalize_email",
    "_normalize_network_tree_item",
    "_normalize_privileges",
    "_now_iso",
    "_order_customer_history_pk",
    "_order_customer_history_sk",
    "_parse_body",
    "_put_associate_month_ref",
    "_put_entity",
    "_put_entity_atomic",
    "_put_network_tree",
    "_query_all_pages",
    "_query_bucket",
    "_query_customer_name_index",
    "_recalc_ledger_totals",
    "_ref_pk",
    "_referral_code_pk",
    "_require_admin",
    "_require_self_or_admin",
    "_require_self_or_admin_from_bearer",
    "_safe_get_item",
    "_save_ledger_month",
    "_send_ses_email",
    "_ses_client",
    "_superadmin_actor",
    "_sync_customer_network_metadata",
    "_table",
    "_to_decimal",
    "_ttl_epoch",
    "_update_by_id",
    "_upsert_customer_email_index",
    "_upsert_customer_name_index",
    "_upsert_order_customer_history",
    "_verify_password",
    "_void_ledger_rows_for_order",
    "base64",
    "boto3",
    "datetime",
    "hashlib",
    "hmac",
    "json",
    "os",
    "register_entity_batch_loader",
    "register_entity_reader",
    "time",
    "timezone",
    "uuid",
]
